In [193]:
import numpy as np
import pandas as pd

1. How likely is it that you roll doubles when rolling two dice?

In [3]:
first_die = np.random.choice ([1, 2, 3, 4, 5, 6], size =  100_000)
second_die = np.random.choice ([1, 2, 3, 4, 5, 6], size =  100_000)
(first_die == second_die).mean()

0.16641

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [47]:
outcomes = [1, 0] # 1 = heads 0 = tails
np.random.choice(outcomes, size = 8)

array([1, 0, 1, 1, 0, 1, 1, 0])

In [60]:
outcomes = [1, 0] # 1 = heads 0 = tails
flips = np.random.choice(outcomes, size = (10_000, 8))
count_heads = flips.sum(axis = 1)
(count_heads == 3).mean()

0.2145

In [228]:
n_simulations = nrows = 1_000_000
n_trials = ncols = 8
heads = 1
tails = 0
flips = np.random.choice([heads, tails], size = (n_simulations, n_trials))
numheads = flips.sum(axis = 1)
calculater_prob = (numheads == 3).mean()
calculater_prob

0.218782

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [237]:
billboard_picks = np.random.choice(["WebDev", "WebDev", "WebDev", "DataScience"], size = (10_000, 2))
billboard_1 = (billboard_picks == "DataScience")
billboard_2 = (billboard_picks == "DataScience")
((billboard_1) & (billboard_2)).mean()

0.25475

In [235]:
n_simulations = nrows = 1_000_000
n_trials = ncols = 2
data_sci = 1
web_dev = 0
commutes = np.random.choice([data_sci, web_dev], size = (n_simulations, n_trials), p = [0.25, 0.75])
calculater_prob = (commutes.sum(axis = 1) == 2).mean()
calculater_prob

0.06229

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?



In [240]:
mu, sigma = 3, 1.5 # mean and standard deviation
pop_consumption = np.random.normal(mu, sigma, size = (10_000, 5))
poptart_qty_on_fri =  17 - pop_consumption.sum(axis = 1)
(poptart_qty_on_fri >= 1).mean()

0.6172

In [241]:
pop_avg = 3
pop_std = 1.5
n_trials = ncols = 5
n_simulations =  1_000_000
simulated_consumed_poptarts =  np.random.normal(pop_avg, pop_std, size = (n_simulations, n_trials))
calculater_prob = (simulated_consumed_poptarts.sum(axis = 1) < 17).mean()
calculater_prob

0.725129

5. Compare Heights



- Men have an average height of 178 cm and standard deviation of 8cm.


In [63]:
mu, sigma = 178, 8 # mean and standard deviation
men = np.random.normal(mu, sigma, 1000)
men

array([180.99221112, 178.43061405, 173.76585417, 187.6882027 ,
       173.73006164, 174.91320605, 175.40979134, 181.06741607,
       179.37883002, 181.45579743, 192.76032407, 165.89139189,
       185.18266759, 183.39825208, 186.1024681 , 177.98833545,
       170.69826866, 181.70416742, 191.53836742, 174.83834004,
       176.67519729, 189.94092441, 172.04032271, 182.21571797,
       180.17380217, 184.61567201, 180.66233939, 170.94122263,
       171.90579943, 174.06035581, 185.28556792, 177.71310997,
       163.83930994, 176.85757029, 181.32670107, 182.61168951,
       177.38785565, 175.17508627, 177.18363984, 170.40545283,
       170.50065577, 184.30880161, 188.72625172, 194.46968224,
       177.28883188, 185.18434169, 186.49664526, 177.76905212,
       194.75001657, 190.93093837, 181.34000883, 181.10352438,
       185.92899748, 171.2425097 , 167.73159223, 176.55500097,
       180.11232751, 176.85698217, 182.1341193 , 184.51374868,
       167.08751985, 177.39196444, 176.01410567, 184.21

- Women have a mean of 170, sd = 6cm.


In [62]:
mu, sigma = 170, 6 # mean and standard deviation
women = np.random.normal(mu, sigma, 1000)
women

array([164.74929087, 170.30315898, 165.91516791, 178.31054781,
       165.07106655, 159.43273848, 168.27021764, 177.53170659,
       171.83791887, 172.21837348, 159.09679202, 171.34454158,
       157.95122351, 166.72426654, 174.14951141, 176.4426729 ,
       171.00124855, 164.75381423, 174.38047605, 171.49939263,
       162.91426886, 171.07669791, 166.29416405, 164.95119687,
       181.67998477, 183.92420599, 172.37908874, 168.88122325,
       159.55225731, 166.09681861, 172.06441647, 169.09886832,
       166.87702003, 150.88996588, 170.29791285, 164.24807449,
       164.55370271, 168.23391606, 171.40699812, 175.97233233,
       168.44621144, 174.6140248 , 178.67636084, 175.19051699,
       162.35698523, 161.84819103, 166.63873923, 174.75368039,
       161.81179959, 166.70117919, 171.21746152, 171.35225343,
       173.22761653, 164.99621353, 178.52799486, 175.00956112,
       170.1306922 , 162.37155999, 173.85135023, 176.66453616,
       168.59155079, 172.96219614, 177.4715251 , 173.52

- If a man and woman are chosen at random, P(woman taller than man)?

In [64]:
(men < women).mean()

0.198

In [245]:
men_avg = 178
men_std = 8
wmn_avg = 170
wmn_std = 6
s_men = np.random.normal(men_avg, men_std, 1_000_000)
s_wmn = np.random.normal(wmn_avg, wmn_std, 1_000_000)
calculated_prob = (s_wmn > s_men).mean()
calculated_prob

0.211753

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?



In [139]:
outcomes = [1, 0]
success_of_50 = np.random.choice(outcomes, size = (10_000, 50), p = [0.996, 0.004])
success_of_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [140]:
successes_50 = success_of_50.sum(axis = 1)
(successes_50 == 50).mean()

0.8152

In [149]:
outcomes = [1, 0]
successes_of_100 = np.random.choice(outcomes, size = (10_000, 100), p = [0.996, 0.004])
successes_of_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [150]:
successes_100 = successes_of_100.sum(axis = 1)
(successes_100 == 100).mean()

0.6749

6a. What is the probability that we observe an installation issue within the first 150 students that download anaconda?



In [146]:
outcomes = [1, 0]
fails_of_150 = np.random.choice(outcomes, size = (10_000, 150), p = [0.004, 0.996])
fails_of_150

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [147]:
failure_150 = fails_of_150.sum(axis = 1)
(failure_150 > 0).mean()

0.4534

In [251]:
n_simulations =  nrows = 1_000_000
n_trials = ncols = 50
conda_failure = 1
conda_success = 0
attempted_class_install = np.random.choice([conda_failure, conda_success], size = (n_simulations, n_trials), p = [0.004, 0.996])
calculated_prob = (attempted_class_install.sum(axis = 1) > 0).mean()
calculated_prob

0.181507

6b. How likely is it that 450 students all download anaconda without an issue?



In [152]:
outcomes = [1, 0]
successes_of_450 = np.random.choice(outcomes, size = (10_000, 450), p = [0.996, 0.004])
successes_of_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [153]:
successes_450 = successes_of_450.sum(axis = 1)
(successes_450 == 450).mean()

0.1615

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [154]:
outcomes = [1, 0]
food_truck_3_days = np.random.choice(outcomes, size = (10_000, 3), p = [0.70, 0.30])
food_truck_3_days

array([[1, 1, 1],
       [1, 0, 1],
       [1, 0, 0],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [156]:
food_truck_3_day_mia = food_truck_3_days.sum(axis = 1)
(food_truck_3_day_mia == 0).mean()

0.0264

7a. How likely is it that a food truck will show up sometime this week?



In [159]:
outcomes = [1, 0]
food_truck_this_week = np.random.choice(outcomes, size = (10_000, 7), p = [0.70, 0.30])
food_truck_this_week

array([[1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 1, 1]])

In [160]:
food_truck_here_this_week = food_truck_this_week.sum(axis = 1)
(food_truck_here_this_week > 0).mean()

0.9999

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [179]:
outcomes = [1, 0]
same_or_dif_birthday_23 = np.random.choice(outcomes, size = (10_000, 23), p = [0.003, 0.997])
same_or_dif_birthday_23

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [180]:
with_same_birthday_23 = same_or_dif_birthday_23.sum(axis = 1)
(with_same_birthday_23 > 0).mean()

0.0644

In [185]:
outcomes = [1, 0]
same_or_dif_birthday_20 = np.random.choice(outcomes, size = (10_000, 20), p = [0.003, 0.997])
same_or_dif_birthday_20

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [186]:
with_same_birthday_20 = same_or_dif_birthday_20.sum(axis = 1)
(with_same_birthday_20 > 0).mean()

0.0591

In [187]:
outcomes = [1, 0]
same_or_dif_birthday_40 = np.random.choice(outcomes, size = (10_000, 40), p = [0.003, 0.997])
same_or_dif_birthday_40

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [188]:
with_same_birthday_40 = same_or_dif_birthday_40.sum(axis = 1)
(with_same_birthday_40 > 0).mean()

0.113

In [253]:
random_birthdays_23 = np.random.choice(range(365), size=(10_000, 23))
random_birthdays_23

array([[322,  43, 363, ..., 265, 276, 246],
       [297, 178, 266, ..., 239, 101, 363],
       [237,  33,  62, ...,  57, 335, 130],
       ...,
       [283,   3, 178, ..., 112, 108, 323],
       [312, 300, 163, ...,  65, 224,  25],
       [188, 216,  74, ..., 178, 129,  15]])

In [254]:
df = pd.DataFrame(random_birthdays_23)

In [255]:
unique_counts = pd.Series(df.nunique(axis=1))
(unique_counts < 23).mean()

0.5071

In [256]:
random_birthdays_20 = np.random.choice(range(365), size=(10_000, 20))
df = pd.DataFrame(random_birthdays_20)
unique_counts = pd.Series(df.nunique(axis=1))
(unique_counts < 20).mean()

0.4082

In [257]:
random_birthdays_40 = np.random.choice(range(365), size=(10_000, 40))
df = pd.DataFrame(random_birthdays_40)
unique_counts = pd.Series(df.nunique(axis=1))
(unique_counts < 40).mean()

0.8923